data:
  data_dataset: "/home/jomoll/dev/maira_rrg/data"
  data_dir: "/home/jomoll/dev/maira_rrg"
  splits_file: "collated_studies_splits.json"
  data_file: "collated_studies_closed_headings_findings5.json"
  mimic_cxr_dir: "/home/jomoll/dev/RaDialog_LLaVA/data/mimic-cxr"
  cache_dir: "processed_data"

model:
  name: "microsoft/maira-2"
  output_dir: "outputs"

training:
  batch_size: 2
  num_epochs: 3
  learning_rate: 2e-5
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  logging_steps: 50
  save_steps: 100
  max_length: 1024
  seed: 42
  gradient_accumulation_steps: 8
  fp16: false
  tf32: true
  gradient_checkpointing: false
  num_gpus: 2
  evaluation_strategy: "steps"
  lazy_preprocess: true
  early_stopping:
    enabled: true
    patience: 10

inference:
  peft_name: "StanfordAIMI/maira2-srrg-findings"
  batch_size: 2
  max_length: 1024
  max_new_tokens: 512
  num_beams: 1
  early_stopping: true


lora:
  r: 128
  alpha: 256
  dropout: 0.0
  target_modules:
    - "q_proj"
    - "v_proj"

wandb:
  project_name: "maira"
  entity: "jomoll-stanford"
  run_name: "train_findings"
