data:
  data_dataset: "/home/alois/ReXrank/maira_rrg/data"
  data_dir: "/home/alois/ReXrank/maira_rrg"
  splits_file: "collated_studies_splits.json"
  data_file: "collated_studies_impression.json"
  mimic_cxr_dir: "/home/alois/ReXrank/RaDialog_LLaVA/data/mimic-cxr"
  cache_dir: "processed_data"

model:
  name: "microsoft/maira-2"
  output_dir: "outputs"

training:
  batch_size: 2
  num_epochs: 3
  learning_rate: 2e-5
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  logging_steps: 50
  save_steps: 100
  max_length: 512
  seed: 42
  gradient_accumulation_steps: 8
  fp16: false
  tf32: true
  gradient_checkpointing: false
  num_gpus: 2
  evaluation_strategy: "steps"
  lazy_preprocess: true
  early_stopping:
    enabled: true
    patience: 10


lora:
  r: 128
  alpha: 256
  dropout: 0.0
  target_modules:
    - "q_proj"
    - "v_proj"

wandb:
  project_name: "maira_rrg"
  entity: "alothomas-stanford-university"
  run_name: "train_impression"
