data:
  data_dataset: "/home/alois/ReXrank/maira_rrg/data"
  data_dir: "/home/alois/ReXrank/maira_rrg"
  splits_file: "collated_studies_splits.json"
  data_file: "collated_studies_closed_headings_findings.json"
  mimic_cxr_dir: "/home/alois/ReXrank/RaDialog_LLaVA/data/mimic-cxr"
  cache_dir: "processed_data"

model:
  name: "microsoft/maira-2"
  output_dir: "outputs"

training:
  batch_size: 2
  num_epochs: 3
  learning_rate: 1e-4
  logging_steps: 10
  save_steps: 500
  max_length: 512
  seed: 42
  gradient_accumulation_steps: 4
  fp16: false
  gradient_checkpointing: false
  num_gpus: 2
  run_name: "train_dev"
  evaluation_strategy: "steps"
  warmup_ratio: 0.3

lora:
  r: 128
  alpha: 256
  dropout: 0.1
  target_modules:
    - "q_proj"
    - "v_proj"

wandb:
  project_name: "maira_rrg"
  entity: "alothomas-stanford-university"
