data:
  data_dataset: "/home/jomoll/dev/maira_rrg/data"
  data_dir: "/home/jomoll/dev/maira_rrg"
  splits_file: "collated_studies_splits.json"
  data_file: "collated_studies_impression4.json"
  mimic_cxr_dir: "/home/jomoll/dev/RaDialog_LLaVA/data/mimic-cxr"
  cache_dir: "processed_data"

model:
  name: "microsoft/maira-2"
  output_dir: "outputs"

training:
  batch_size: 2
  gradient_accumulation_steps: 16
  num_epochs: 5
  learning_rate: 1e-4
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  logging_steps: 10
  save_strategy: "steps"
  save_steps: 200
  seed: 42
  fp16: true
  tf32: true
  bf16: false
  gradient_checkpointing: false
  num_gpus: 1
  evaluation_strategy: "steps"
  eval_steps: 200
  lazy_preprocess: true
  early_stopping:
    enabled: true
    patience: 3

inference:
  peft_name: "StanfordAIMI/maira-2-srrg-impression"
  batch_size: 2
  max_new_tokens: 512
  num_beams: 5
  early_stopping: true


lora:
  r: 128
  alpha: 256
  dropout: 0.0
  target_modules:
    - "q_proj"
    - "v_proj"

wandb:
  project_name: "maira_rrg"
  entity: "jomoll-stanford"
  run_name: "train_findings"
